contentdir: "content"
layoutdir: "layout"
publishdir: "public"
baseurl: "http://www.thezymologist.com"
params:
  Description: "A site for all things related to the science and art of fermentation"
languageCode: "en-us"
title: "The Zymologist"
disqusShortname: "thezymologist"
